### ISSUE TITLE
customize the style of <td>

### ISSUE THREAD

**Issue by yakiang** [jmaister/excellentexport#11]
Hi, cool repo!
In my table, some `<td>` may contain `href` (might be `javacript:void(0)`) , some may be set to `display:none`, and I don't want them in the final `.xls` file.  So I'm wondering if there's any way to do it, by an `option` for example ?

**Comment by phun-ky** [comment]
If the developer (owner or contributor) does something like this:

     tab_text= tab_text.replace(/<A[^>]*>|<\/A>/g, "");//remove if u want links in your table
     tab_text= tab_text.replace(/<img[^>]*>/gi,""); // remove if u want images in your table
     tab_text= tab_text.replace(/<input[^>]*>|<\/input>/gi, ""); // removes input params

Of the table text, it could work
