### ISSUE TITLE
Large table crashes Chrome

### ISSUE THREAD

**Issue by zbend** [jmaister/excellentexport#12]
I have a 73 column, 219 row table (yeah don't ask), trying to export it crashes Chrome, FYI.
(well it crashes the Chrome tab)

**Comment by eescobar** [comment]
+1

**Comment by riccardo-db** [comment]
tag<b>tag</b>pippo

**Comment by jmaister** [comment]
I can't do anything about this.

After some tests, I found that Chrome fails when the file is about 1.5 MB.

**Comment by craignicol** [comment]
The Chrome recommended solution appears to be to use getObjectURL for anything larger than 2MB : https://bugs.chromium.org/p/chromium/issues/detail?id=69227
