### ISSUE TITLE
Cannot read property 'csv' of undefined

### ISSUE THREAD

**Issue by LiranBN** [jmaister/excellentexport#131]
I am new with angular and I am trying to use it in type script.
in my component I imported the ExcellentExport like this:
 import { ExcellentExport } from 'excellentexport';

and created  function 
export(item: any, name: string):void {
    return ExcellentExport.csv(item, name);
  }

and in the html  I called like this :
<a download="somedata.csv" href="#" (click)="export(this, 'subjectsTable')">Export to CSV</a>

but I get this error when I am clicking the link : 
Cannot read property 'csv' of undefined

**Comment by jmaister** [comment]
Which version of ExcellentExport are you using ?
Could you post the relevant parts of your package.json ?

**Comment by jmaister** [comment]
Not a defect.
