### ISSUE TITLE
Border: solid 1px does not work in IE 11

### ISSUE THREAD

**Issue by xungegeblue** [jmaister/excellentexport#176]
This tool really works!

I found a problem in the process of using it, and I need your help 
This is my code
```
html
<table>
....
<td style="text-align: center;border: solid 1px">some data</td>
....
</table> 
```
```
js
ExcellentExport.excel(event.target, 'datatable', `name.xlsx`)
```
I use the latest version of ExcellentExport
The above code can display table style well in Google browser, but in Internet explorer, excel table (td, th) does not display border

**Comment by jmaister** [comment]
Styles in the HTML table do not affect the final Excel.
ExcellentExport does not handle Excel styles.
