### ISSUE TITLE
Exporting CSV & Excel with IE 

### ISSUE THREAD

**Issue by riccardo-db** [jmaister/excellentexport#19]
var ee = {
        /** @expose */
        excel: function(anchor, table, name, filename) {
        	if (!filename) var filename = 'output.xls'; 
            table = get(table);
            var ctx = {worksheet: name || 'Worksheet', table: table.innerHTML};
            var isIE = /*@cc_on!@*/false || !!document.documentMode;
            if((navigator.appVersion.indexOf("MSIE") >= 0) || (isIE == true)) {
	            myFrameTableDownloadIE.document.open("text/html", "replace");
	            myFrameTableDownloadIE.document.write(format(template.excel, ctx));
	            myFrameTableDownloadIE.document.close();
	            myFrameTableDownloadIE.focus();
	            myFrameTableDownloadIE.document.execCommand('SaveAs', true, filename);            
            } else {
                var hrefvalue = uri.excel + base64(format(template.excel, ctx));
                anchor.href = hrefvalue;
            }
            // Return true to allow the link to work
            return true;
        },
        /** @expose */
        csv: function(anchor, table, delimiter, newLine, filename) {
        	if (!filename) var filename = 'output.csv';
            if (delimiter !== undefined && delimiter) {
                csvDelimiter = delimiter;
            }
            if (newLine !== undefined && newLine) {
                csvNewLine = newLine;
            }
            table = get(table);
            var csvData = tableToCSV(table);
            
            var isIE = /*@cc_on!@*/false || !!document.documentMode;
            if((navigator.appVersion.indexOf("MSIE") >= 0) || (isIE == true)) {
	            myFrameTableDownloadIE.document.open("text/html", "replace");
	            myFrameTableDownloadIE.document.write(csvData);
	            myFrameTableDownloadIE.document.close();
	            myFrameTableDownloadIE.focus();
	            myFrameTableDownloadIE.document.execCommand('SaveAs', true, filename);            
            } else {
	            var hrefvalue = uri.csv + base64(csvData);
	            anchor.href = hrefvalue;
            }
            return true;
        }

**Comment by sudhirravindramohan** [comment]
Please check https://www.linkedin.com/pulse/script122-data-area-passed-system-call-too-small-ie-ravindramohan for a simpler solution.
