### ISSUE TITLE
Arrow syntax causes problem in IE 11

### ISSUE THREAD

**Issue by brockfanning** [jmaister/excellentexport#197]
Around version 3.3.0 there was some arrow syntax introduced in in excellentexport.js ([here](https://github.com/jmaister/excellentexport/blob/master/excellentexport.js#L197) and [here](https://github.com/jmaister/excellentexport/blob/master/excellentexport.js#L225)) and it's making it into dist/excellentexport.js. I'm the last person to ask about transpilation best-practices, but I'm under the impression that dist/excellentexport.js is intended to be ready-to-use without any transpiling. If I'm right about that, and if IE 11 support is still wanted, should that be fixed?

If so, I imagine it could either be done with transpilation or by just using regular function syntax instead of arrow syntax. I imagine that the former is preferred there, so you're not doomed to using old-style javascript.

I'll put up a PR for this shortly, in case my assumptions are right and it's helpful.

**Comment by jmaister** [comment]
I didn't notice about those arrow functions going into the final dist file.

Probably will be easier to transform then into function() {...} than configuring a transpiler. However, I have no preference about using it.

**Comment by brockfanning** [comment]
@jmaister I did have some trouble with setting up transpiling, so I'm happy to use the normal function syntax. I've opened a PR for this: #199
