### ISSUE TITLE
Make exceptions for certain columns?

### ISSUE THREAD

**Issue by savraj** [jmaister/excellentexport#20]
So I have a column that I don't want to appear in the exported Excel file (this column contains buttons/links that only work on the web) -- Maybe mark cells to exclude with a certain CSS class or something. Like 
`<td data-excel-export-exclude="true">my buttons are here</td>`
or something of the sort.

**Comment by jmaister** [comment]
I'll be adding filter functions for rows and columns. Not designed how it will work yet.

**Comment by jmaister** [comment]
Implemented on #88 
https://github.com/jmaister/excellentexport/tree/3.3.0
