### ISSUE TITLE
JS is exported if cell contains <script>

### ISSUE THREAD

**Issue by smenzer** [jmaister/excellentexport#21]
I have some cells that need to execute some JS, so the cell contains <script>var someJS = 'some value';</script>.  When I export, "var someJS = 'some value';" is included in the Excel cell, which is not ideal.  I've worked around this by adding additional checks in the regex to find <script></script> tags and add html comments around them so that Excel doesn't display them, but I'd like that built in so I don't have to use a custom version of the script.

Additional hacky code added around line 104 in the ExcellentExport function definition

``` javascript
// comment out scripts so the JS doesn't appear in Excel
c.table = c.table.replace(new RegExp("<script", "g"), function(m,p) {
    return "<!-- <scr"+"ipt";
});
c.table = c.table.replace(new RegExp("</script>", "g"), function(m,p) {
    return "</scr"+"ipt> -->";
});
```

**Comment by jmaister** [comment]
Filtering values. Repeated on #15
