### ISSUE TITLE
Maybe need to set border.

### ISSUE THREAD

**Issue by wind13** [jmaister/excellentexport#22]
This project is simple enough and useable! Great!
But I think many usage is to export html table to excel report, so I think there is border in excel will be better for custom.

So if this project can config border or just set table style for border, it may be great.

**Comment by aykutkardas** [comment]
Cell formatting should be added.

For example,
Numerical values in the table, opens as a date.

**Comment by jmaister** [comment]
Formatting and styles would require to write the full Office XML specification in JavaScript.

This features are not intended in this project.

**Comment by wind13** [comment]
This border can be done by <table border="1">, look at my project: https://github.com/wind13/jsxlsexport
