### ISSUE TITLE
Embed base64 image into the Excel

### ISSUE THREAD

**Issue by elaijuh** [jmaister/excellentexport#23]
Is it possible to embed an `<img>` with base64 source into the Excel? ie. open the Excel with image show normally.

**Comment by dexter777** [comment]
I tested this by directly editing file created by excellentexport, it seems excel 2007 doesn't support base64 encoded images. Only properly linked images work, eg <img src="http://link.to/some/image.jpg"> but i didnt'e test if excellentexport support exporting them from website code

**Comment by zjhiphop** [comment]
I have the same requirement, hope has a solution.

**Comment by wbswbs** [comment]
To remove the Images from the Export (and Links), you can use 

    var filter = function (table_content){
        // Remove Images
        table_content = table_content.replace(/(<img([^>]*)[^<]+>)/gi, '');
        //var replace_img_with_class = /(<img[^<]+class=[\"'][^<]*\s*thumbnail\s*[^<]*[\"'][^<]+>)/ig;
        // Remove Links
        table_content = table_content.replace(/(<a(?:(?!\/a>).|\n)*(?=\/a>)...)/gi, '');
        return table_content;
   }
excel: function(anchor, table, name) {
            table = get(table);
            var ctx = {worksheet: name || 'Worksheet', table: filter(table.innerHTML)};
}

**Comment by jmaister** [comment]
Duplicated #65
