### ISSUE TITLE
How to hide HTML td when exporting to Excel?

### ISSUE THREAD

**Issue by maliyogesh** [jmaister/excellentexport#24]
When export to excel how to add the CSS class to any tr tags to ignore the specified table data while exporting.Is this possible?

**Comment by mbcorona** [comment]
if you are using jquery, you can change the excel function by this:
excel: function (d, a, b, i) {
                var html = $("#" + a).clone();
                if(i != undefined)
                    html.find("th:nth-child(" + i + "), td:nth-child(" + i + ")").remove();
                a = window.btoa(window.unescape(encodeURIComponent(l('<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head><meta name=ProgId content=Excel.Sheet/> <meta name=Generator content="Microsoft Excel 11"><meta http-equiv=Content-Type content="text/html; charset=UTF-8">\x3c!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>{worksheet}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--\x3e</head><body><table>{table}</table></body></html>', {
                    worksheet: b || "Worksheet",
                    table: html.html()
                }))));
                return n(d, a, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "export.xls")
            },

the i parameter, indicates the column you don't want to see. Notice that starts from 1

**Comment by jmaister** [comment]
Filtering values. Repeated #15
