### ISSUE TITLE
<br> in html table is shown as <br> instead of new line in csv

### ISSUE THREAD

**Issue by subinbalan2409** [jmaister/excellentexport#277]
<br> in html table is shown as <br> instead of new line in csv

I tried changing the html to add <td>Text <br>line</td>, but in the exported csv file its shwoing as such <td>Text <br>line</td> instead of new line. Can you pls let me know how I can fix it?

**Comment by jmaister** [comment]
You can use the parameter "filterRowFn". This parameter is a function that will receive each row. You can modify each column of the row to replace "<br>" by "\n".

**Comment by jatzqo** [comment]
Hi! 
Could you help me to resolve this error?

![2020-07-14](https://user-images.githubusercontent.com/52256146/87487023-3767b880-c602-11ea-9ac9-9e724bcc19e6.png)

**Comment by jmaister** [comment]
This can be solved with the new configuration functions fixValue and fixData. Check the documentation and index.filters.html to see how they work.

Those functions can be used to manipulate the cell values before the Excel file is generated.
