### ISSUE TITLE
Office: "The file format differs from the format that the file name extension specifies"

### ISSUE THREAD

**Issue by cosmocracy** [jmaister/excellentexport#28]
Looks like Office 2007 and beyond have an extension check that is getting triggered when running even the examples, causing an error "The file format differs from the format that the file name extension specifies"

See: https://support.microsoft.com/en-us/kb/948615

**Comment by craignicol** [comment]
It's worse than that - there's a new Microsoft patch out that means that Excel will refuse to open such files if they are untrusted : https://social.technet.microsoft.com/Forums/en-US/d2d84793-9920-45e3-baef-5027a4ac1ae0/kb3170008-for-office-2016-breaks-functionality-ms16088

**Comment by laviyatziv** [comment]
Running into this now. These files are also broken in Office 360.

**Comment by luizeduard0** [comment]
Is there any fix for this?

**Comment by jmaister** [comment]
Next versions will support XLSX.

Will fix on #71
