### ISSUE TITLE
Gridlines not shown

### ISSUE THREAD

**Issue by dackmin** [jmaister/excellentexport#29]
Even if `<x:DisplayGridlines/>` is present in xls template, gridlines are not shown when opened in Excel (Excel 2011 Mac OS).

I had to add `<meta name=ProgId content=Excel.Sheet> <meta name=Generator content="Microsoft Excel 11">` to template, just before `<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">` to make them appear.

**Comment by jy1989** [comment]
thank you. very helpful .
