### ISSUE TITLE
Support for typescript

### ISSUE THREAD

**Issue by ldsenow** [jmaister/excellentexport#302]
Hi there,

I have encountered an issue in Typescript. "Could not find a declaration file for module 'excellentexport'"

Would be good to have TS support.

**Comment by PaulloClara** [comment]
I haven't mapped the entire code yet, and what has already been done needs validation, but I believe it works... [my attempt](https://github.com/PaulloClara/excellentexport/tree/feature/typescript)

**Comment by jmaister** [comment]
Would transforming the whole project to TypeScript help to this?

I would like to keep allowing users to just add a JavaScript script tag to the compiled version in any HTML page and keep it working.

**Comment by jmaister** [comment]
Fixed!!
The project now is done using TypeScript. #418
