### ISSUE TITLE
Numbers treated as octal and leading zero are missing

### ISSUE THREAD

**Issue by ofirk** [jmaister/excellentexport#31]
Each cell that start with leading zero will output without the leading zero or zeros.
Can I pass the data as string to the new excel file?
Will be glad to find a solution. thanks!

**Comment by Emi-C** [comment]
I have the same problem, did you eventually solve it?

**Comment by Emi-C** [comment]
For anybody who might need it, I solved adding &emsp; before my output (e.g. <td>&emsp;<numericOutputStartingWith0></div>)

**Comment by jmaister** [comment]
I tried to add <td>0123</td> to a cell and it is exported as number 123.

Would you provide a failing sample ?

**Comment by Emi-C** [comment]
That is a failing example.
If we want to export telephone numbers for instance, which in italy start with a 0, we have to add a &emsp before the actul number:
&emsp;0332222240 is exported as 0332222240
0332222240 id exported as 332222240

**Comment by SangKa** [comment]
I thought this issue can be fix if can find a way to specify the cell format of the excel to the normal text in the html.

**Comment by rneuber1** [comment]
I have made some modifications, see commit https://github.com/jmaister/excellentexport/pull/64/commits/652c211f823f91fc40437ac235414c24d1c8bcd1 
This allows to define a format for cells, thus allowing for treating leading zeroes correctly:

![image](https://cloud.githubusercontent.com/assets/6908002/24955677/b95f8f7a-1f84-11e7-85b4-37ebcfd0e8ef.png)

results in:

![image](https://cloud.githubusercontent.com/assets/6908002/24955663/a329d990-1f84-11e7-9623-2058764cc153.png)

**Comment by SangKa** [comment]
awesome work

**Comment by jmaister** [comment]
Fixed on version 3.0.0

**Comment by jmaister** [comment]
@cuiyajie Would you provide an example of the TABLE used and the generated file ?
