### ISSUE TITLE
Data display in mess when export large data to excel

### ISSUE THREAD

**Issue by JacktarLiu** [jmaister/excellentexport#32]
I export a table with rowspan to excel, it works well when data were not  large , but if i export large data from table to excel, the data display in mess .And I found the issue usually happened from 3856th row ,no matter which record in that row.
![image](https://cloud.githubusercontent.com/assets/13634392/9377978/2f9fee96-4750-11e5-8754-b47404a2fa97.png)

**Comment by jmaister** [comment]
Please, provide sample data.
