### ISSUE TITLE
Chrome crashed

### ISSUE THREAD

**Issue by kaushiik** [jmaister/excellentexport#34]
If I am going to export large amount of data like 4000 rows then it will crashed.

What should i do to solve this issue?

**Comment by mbenyoub** [comment]
The solution is here:
http://stackoverflow.com/questions/23301467/javascript-exporting-large-text-csv-file-crashes-google-chrome

**Comment by kaushiik** [comment]
Thanks.

**Comment by craignicol** [comment]
I have a pull request #44 that applies the fix discussed in that stackoverflow link.

**Comment by jmaister** [comment]
Fixed with #44 and #48
