### ISSUE TITLE
HTML Problem

### ISSUE THREAD

**Issue by MustafaKarabulut** [jmaister/excellentexport#340]
Hi,

Thank you and congratulations for your work.

I'm currently trying to understand the capabilities of the library and could not understand how it treats to HTML content.

1- If the following type of code is used to invoke the library, it accepts HTML tags like `<b>text</b>`
`ExcellentExport.excel(this, 'tableId', 'tableLabel')`

2- If I give the data via the api options like in the following snippet, it takes HTML tags as a part of the text:
`ExcellentExport.convert({
		anchor: aObj,
		filename: 'fileName',
		format: 'xls'
		},
		[{
			name: 'Table Label',
		from: {
			array: [ ['1', 'normal text'], ['2', '<b>Bold text</b>'] ]
		},
	}]);`

I would like to use some HTML tags inside a cell to stylize the content to an extent. How can I achieve this by using API's from: array syntax?

Thanks in advance

**Comment by jmaister** [comment]
Hi @MustafaKarabulut ,

You can't style your cells in Excel with HTML or CSS. Excel is going to deal with the HTML as text.

This library does not support any kind of style for the resulting CSV or Excel files.

**Comment by jmaister** [comment]
Thanks for the investigation, very good catch.

`ExcellentExport.excel` only generates `XLS`, and it works with the "trick" of exporting an HTML table. So, if any HTML works is just a side effect of it, not on pourpose of this library.

`ExcellentExport.convert` is used to generate `XLSX`, that is a very different file format. As I am using `js-xlsx.utils.aoa_to_sheet`, there is no control on how the HTML is handled internally.

This library is not meant to handle HTML for styling.
