### ISSUE TITLE
Invalid package version for rails-assets.org

### ISSUE THREAD

**Issue by Minisai** [jmaister/excellentexport#35]
Hi @jmaister 

I use https://rails-assets.org/ for package managing of JS libraries for my Ruby on Rails project and forced a problem with excellentexport gem generating. You can see it [here](https://rails-assets.org/components/new). It writes "excellentexport has no versions defined. Please create an issue in component's repository.".

The problem is that you use 2-digit version number and this is not [Semantic Versioning](http://semver.org/spec/v2.0.0.html). 

Could you please publish new github release with 3 digit (like 1.5.0)?

**Comment by jmaister** [comment]
On release 2.0.0 I'll add the version with the SEMVER system.

**Comment by jmaister** [comment]
Fixed on version 2.0.0.
