### ISSUE TITLE
readme 文档的用法有错误？

### ISSUE THREAD

**Issue by youxianbo** [jmaister/excellentexport#371]
这部分文档：
Sheet element configuration:
 {
    name: 'Sheet 1', // Sheet name
    from: {
        table: String/Element, // Table ID or table element
        array: [...], // Array with data
        arrayHasHeader: true, // Array first row is the header
        removeColumns: [...], // Array of column indexes (from 0)
        filterRowFn: function(row) {return true}, // Function to decide which rows are returned
        fixValue: function(value, row, column) {return fixedValue} // Function to fix values, receiving value, row num, column num
        fixArray: function(array) {return array} // Function to manipulate the whole data array
    },
    ...
 }

使用了这几个方法发现没有被调用，查看源代码才发现方法是要在from这个对象的外面，这样才是对的（arrayHasHeader  这个好象并没有用？）：
 {
    name: 'Sheet 1', // Sheet name
    from: {
        table: String/Element, // Table ID or table element
        array: [...], // Array with data
        arrayHasHeader: true, // Array first row is the header
    },
        removeColumns: [...], // Array of column indexes (from 0)
        filterRowFn: function(row) {return true}, // Function to decide which rows are returned
        fixValue: function(value, row, column) {return fixedValue} // Function to fix values, receiving value, row num, column num
        fixArray: function(array) {return array} // Function to manipulate the whole data array
    ...
 }

代码在excellentexport.js 217行左右

**Comment by jmaister** [comment]
Translation:

> After using these methods, I found that it was not called. I checked the source code and found that the method should be outside the from object. This is correct (arrayHasHeader does not seem to be useful?

You are right, arrayHasHeader is not being used. It should be used to when the data is loaded.

I'll create a Pull Request in the next days.

**Comment by jmaister** [comment]
Fixed.
