### ISSUE TITLE
Update Readme please

### ISSUE THREAD

**Issue by bresleveloper** [jmaister/excellentexport#392]
1st - In the Readme you specify ` ExcellentExport.convert(options, sheets);` and then example to sheet configuration.
Please specify that `sheets param MUST be an array of  sheet configuration objects`

2nd - In the Readme you specify `array: [...], // Array with data`, but its actually must be an array or arrays, array or object will cause an error. Please specify that `array MUST an array or arrays // ex: [['col1_value', 'col2_value'], [...]] `

3rd - `arrayHasHeader` is not in use in the code, and should be removed from the Readme

In order to solve these issues for myself I had to look into your code, and into [a sheetjs tutorial](https://redstapler.co/sheetjs-tutorial-create-xlsx/)

**Comment by jmaister** [comment]
Thanks @bresleveloper for finding this.

I'll update the README.md for the next release.

**Comment by jmaister** [comment]
Fixed on #415
