### ISSUE TITLE
Documentation/code discrepancy

### ISSUE THREAD

**Issue by TheWildHorse** [jmaister/excellentexport#398]
Hello,
thanks for the awesome lib.

I found a error in the docs with the fixValue feature (others might be affected as well).

```
 {
    name: 'Sheet 1', // Sheet name
    from: {
        table: String/Element, // Table ID or table element
        array: [...], // Array with data
        arrayHasHeader: true, // Array first row is the header
        removeColumns: [...], // Array of column indexes (from 0)
        filterRowFn: function(row) {return true}, // Function to decide which rows are returned
        fixValue: function(value, row, column) {return fixedValue} // Function to fix values, receiving value, row num, column num
        fixArray: function(array) {return array} // Function to manipulate the whole data array
    },
    ...
 }
```

Here the fixValue parameter is said to be used within the "from" parameter, but the code searches it in the parent element. 

Example based on info from the docs:
`return ExcellentExport.convert({ anchor: this, filename: 'welcome-mail-recipients.xlsx', format: 'xlsx'},[{name: 'Recipients', from: {table: 'datatable', fixValue: newLineAndHtmlStripFix}}]);`

Example that actually works:
`return ExcellentExport.convert({ anchor: this, filename: 'welcome-mail-recipients.xlsx', format: 'xlsx'},[{name: 'Recipients', from: {table: 'datatable'}, fixValue: newLineAndHtmlStripFix}]);`

Didn't make a pull since I do not know which one you wanted to use.

**Comment by jmaister** [comment]
Thanks @TheWildHorse
This has bee fixed in #403
