### ISSUE TITLE
problem using ExcellentExport.convert without anchor

### ISSUE THREAD

**Issue by Nebules** [jmaister/excellentexport#408]
This is a great function, but I'd like to figure out how to use it WITHOUT the anchor option, to mesh with my application. 

Here's a fiddle of what I'm trying to get working:

[https://jsfiddle.net/Nebules/k32pc7oz/2/](url)

I get the error "Error: Error converting to xlsx. TypeError: e is undefined"

**Comment by jmaister** [comment]
If there is no anchor, how do you want to trigger the file download ?

**Comment by benrosati** [comment]
For the client site which I was working on, the functionality requested was to have an option to download an excel file containing the user inputted form data. So a table would have to be made on user-interaction. User should be expected to only have to click a button once.

My solution was to hide a button, which is then activated with click().

If it helps, here is the snippet of code.

`
			$('.fs-export-btn--csv').on('click', function(){

				var form = $(this).closest('.fs-form');
				var table = $('.fs-export-csv table');
				tableRows = '';

				form.find('.fs-form-fieldset').each(function(i, el){
					var label = $(el).find('h3').text();
					$(el).find('textarea:visible').each(function(ii, elel) {
						var sum = parseInt( $(elel).val() );
						if( $.isNumeric(sum) ){
							if ( $(el).attr('data-function') == "add" ) {
								sum = Math.abs(sum);
							} else {
								sum = -Math.abs(sum);
							}
							tableRows = tableRows + '<tr><td>'+label+'</td><td>'+sum+'</td></tr>';
						}
					});
				});
				
				table.find('tbody').html(tableRows);

				ExcellentExport.convert({
					anchor: $('.fs-export-btn--pdf--hack')[0],
					format: 'xlsx',
					filename: 'Budgeting-Worksheet'
				},[{
					name: 'Sheet 1',
					from: {table: $('.fs-export-csv table')[0]}
				}]);

				$('.fs-export-btn--pdf--hack')[0].click();

			});
`

Thank you jmaister for all your hard work on this.

**Comment by alfanzain** [comment]
> If there is no anchor, how do you want to trigger the file download ?

Click by <button> ?

**Comment by jmaister** [comment]
Fixed this by creating an anchor tag and attaching the blob to download the file.

Check the file `index.noanchor.html` for an example.

    ExcellentExport.convert({
        filename: 'fileTriggeredAutomatically',
        format: 'xlsx',
        openAsDownload: true // NEW OPTION !!!
    },
         [...]);
