### ISSUE TITLE
Add support for exporting csv with Chinese characters(Windows platform) | 解决导出csv中文乱码问题

### ISSUE THREAD

**Issue by lixuanbin** [jmaister/excellentexport#42]
Find this line(in function csv):
```
var hrefvalue = uri.csv + base64(csvData);
```
change it to:
```
var hrefvalue = uri.csv + '77u/' + base64(csvData);
```

**Comment by jmaister** [comment]
I just tried to export a table with Chinese characters and it worked without that BOM char.

Could you provide any example of your error ?
