### ISSUE TITLE
The downloaded file was the HTML page itself.

### ISSUE THREAD

**Issue by shipherd** [jmaister/excellentexport#440]
Hi, I am trying to convert a table and save it as a xlsx file.

HTML:
`<a href="#" download="export.xlsx" onclick="exportClick()">Export</a>`

JS:
`
function exportClick(){
    return ExcellentExport.convert(
        { 
            anchor: this, 
            filename: 'test', 
            format: 'xlsx'
        },
        [
            {
                name: 'Sheet Name Here 1', 
                from: {
                    table: 'resultTable'
                },
                removeColumns: [0, 6 ,7]
            }
        ]
        );}
`

Not sure why the file 'export.xlsx' contains only the HTML page itself.
![image](https://user-images.githubusercontent.com/34145945/108938485-20567200-768b-11eb-8fdf-b951197a5762.png)

Any help? thank you.

**Comment by jmaister** [comment]
It looks like you are calling the function when the <a> is defined:

    <a href="#" download="export.xlsx" onclick="exportClick()">Export</a>

It should be done like this, only referencing the function to be used:

    <a href="#" download="export.xlsx" onclick="exportClick">Export</a>

**Comment by shipherd** [comment]
> It looks like you are calling the function when the is defined:
> 
> ```
> <a href="#" download="export.xlsx" onclick="exportClick()">Export</a>
> ```
> 
> It should be done like this, only referencing the function to be used:
> 
> ```
> <a href="#" download="export.xlsx" onclick="exportClick">Export</a>
> ```

The problem remains after changing the function to be referenced.

**Comment by shipherd** [comment]
> It looks like you are calling the function when the is defined:
> 
> ```
> <a href="#" download="export.xlsx" onclick="exportClick()">Export</a>
> ```
> 
> It should be done like this, only referencing the function to be used:
> 
> ```
> <a href="#" download="export.xlsx" onclick="exportClick">Export</a>
> ```

The problem can be resolved if I embed the JS code into HTML, which just like what the example did.
