### ISSUE TITLE
amp; causing column separation

### ISSUE THREAD

**Issue by ah-des** [jmaister/excellentexport#47]
If your table header field name has `&amp;` in it then it will separate it out as two separate columns

**Comment by wbswbs** [comment]
Proposal: Using Filters:

    var content_filter = function (table_content){

        // Remove Images
        table_content = table_content.replace(/(<img([^>]*)[^<]+>)/gi, '');

        console.log(table_content);

        // Remove Links
        table_content = table_content.replace(/(<a(?:(?!\/a>).|\n)*(?=\/a>)...)/gi, '');

        // Remove Ampersand
        table_content = table_content.replace(/(&amp;)/gi, '');

        console.log(table_content);

        return table_content;
    };
    var ee = {
        /** @expose */
        excel: function(anchor, table, name) {
            console.log(table);
            table = get(table);
            console.log(table);
            var ctx = {worksheet: name || 'Worksheet', table: content_filter(table.innerHTML)};
            var hrefvalue = uri.excel + base64(format(template.excel, ctx));
            anchor.href = hrefvalue;
            // Return true to allow the link to work
            return true;
        },

**Comment by jmaister** [comment]
Ampersand is working on TD and TH.

![2016-10-03 23_40_12-somedata 11 xls protected view - excel](https://cloud.githubusercontent.com/assets/374021/19056704/c763dc6e-89c2-11e6-930c-329a55e3fce1.png)
