### ISSUE TITLE
Firefox Error: Argument 2 of URL.createObjectURL can't be converted to a dictionary.

### ISSUE THREAD

**Issue by snuuve** [jmaister/excellentexport#54]
Error in Firefox (50.0):

![fifrefox excel errro](https://cloud.githubusercontent.com/assets/9519759/20389594/a6c668ca-acca-11e6-897e-d42a91c61813.PNG)

**Comment by craignicol** [comment]
Temporary fix discussed on the Blob PR here https://github.com/jmaister/excellentexport/pull/48#issuecomment-255954805

>The Firefox error persists in the 2.0.0 version (downloaded today) for Firefox 49.0.1 when using the CSV export.
> A temporary fix involves replacing "exporttype" on line 105 with
{ type : exporttype}

Same fix will work for XLS

**Comment by jehon** [comment]
I had the same problem today, with the bower download of version 2.0.0.

The fix mentionned by @gspringtech in @craignicol comment is working.

What about integrating that in the trunk?

Thanks
