### ISSUE TITLE
XLSX file size is large and decreases significantly after editing.

### ISSUE THREAD

**Issue by Sonchucks** [jmaister/excellentexport#554]
When doing a slight edit to an exported XLSX file, I've noticed that the file size ends up decreasing. I had exported a file that was initially 24kb, which after editing went down to ~10kb. The larger the file, the more significant the decrease in file size.

Looking into this, it seems like the `xlsx` package that `excellentreport` uses has an option to compress files to decrease the file size for ZIP type files (which this would fall under).

https://github.com/SheetJS/sheetjs#writing-options

I didn't actually test out whether this would actually fix the issue I've noticed. However, was wondering if it'd be possible to make a change that would allow the consumers of this package to send down additional options to the `xlsx` package.

Could do something like this

```
const convert = function(options:ConvertOptions, sheets:SheetOptions[], additionalOptions:AdditionalOptions) {
  ...
    const worksheet = XLSX.utils.aoa_to_sheet(dataArray, {sheet: name, ...additionalOptions} as XLSX.AOA2SheetOpts);
  ...
}
```

Either that or allow these additional options to be part of the ConvertOptions.

**Comment by jmaister** [comment]
Fixed. Will be activated by default in the next version.
