### ISSUE TITLE
Firefox Error (TypeError: Argument 2 of URL.createObjectURL can't be converted to a dictionary)

### ISSUE THREAD

**Issue by ErunamoJAZZ** [jmaister/excellentexport#56]
Hello, we were testing in Firefox developer edition (Linux 64bits 52.0a2 now, but its same in FF stable) the index.html, but that does not work. That was the error:

```
TypeError: Argument 2 of URL.createObjectURL can't be converted to a dictionary.[Learn More]  excellentexport.js:105:27
```

The "Learn More" is a link to https://developer.mozilla.org/docs/Web/JavaScript/Reference/Errors/No_properties?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default

The problem is that `window.URL.createObjectURL()` only receive one argument (the blob): https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL

**Comment by jmaister** [comment]
Merged #57
