### ISSUE TITLE
Missing bold on header for XLSX format

### ISSUE THREAD

**Issue by fgcalderon-pdevs** [jmaister/excellentexport#575]
This is my HTML markup for my Heading row

```
<thead>
 <tr>
	<th>Expense</th>
	<th>Cost</th>
 </tr>
</thead>
```

But when I export it the header row is not bold

![image](https://user-images.githubusercontent.com/85312127/127349593-245147e6-ae19-4e5f-b844-262671a1c067.png)

**Comment by jmaister** [comment]
ExcellenExport does not handle cell formatting and it is not planned to implement.
