### ISSUE TITLE
missing file: bootstrap.min.css

### ISSUE THREAD

**Issue by augustogoncalves** [jmaister/excellentexport#60]
With version 2.2 I'm getting this error when trying to open the file (MacOS), was working on previous versions. 
![screen shot 2017-01-12 at 09 51 08](https://cloud.githubusercontent.com/assets/4291593/21888754/c4e4a912-d8ac-11e6-8166-2a70d591c414.png)
Yes I use Bootstrap on my page, yes the table have some images (but it was working before)

**Comment by mbcorona** [comment]
try adding bootstrap cdn on excel function, just before the end of the Head tag
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> 
like this:
a = window.btoa(window.unescape(encodeURIComponent(l('<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"><head><meta name=ProgId content=Excel.Sheet/> <meta name=Generator content="Microsoft Excel 11"><meta http-equiv=Content-Type content="text/html; charset=UTF-8">\x3c!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>{worksheet}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--\x3e</head><body><table>{table}</table></body></html>', {

**Comment by jmaister** [comment]
Bootstrap is not related with this library.
