### ISSUE TITLE
Space as Separator for  exporting to .csv

### ISSUE THREAD

**Issue by khirunnisa** [jmaister/excellentexport#646]
Hello,  I’ve been using your code (ExcellentExport.js) to put my html result into Formatted Text( Space Delimited) (*.prn).
I have a question, Is it possible if I want to use space as separator, not semicolon?

Thank you in advance.

**Comment by jmaister** [comment]
If you are using ExcellentExport.csv(...) you can add the "delimiter" parameter.

    csv: function(anchor:(HTMLAnchorElement|string), table:HTMLTableElement, delimiter?:string, newLine?:string)

For example:

    ExcellentExport.csv(getElementById('link'), getElementById('table'), ' '); // The last parameter here is a space.

If you are using ExcellentExport.convert(...) there is no option yet. It will need some changes in the code.
