### ISSUE TITLE
table checkbox  Export selected rows (csv)

### ISSUE THREAD

**Issue by eric-5512** [jmaister/excellentexport#654]
HI @jmaister 
![image](https://user-images.githubusercontent.com/56282991/142881795-1de2d512-4cad-4058-8989-0ce5d08a9981.png)

**Comment by jmaister** [comment]
Hi @eric-5512, please add more information. What is your current output? What do you want to accomplish?

**Comment by eric-5512** [comment]
HI @jmaister 

1:Now you can only export all the data of the table.

2:I expect to export only the data I selected.

**Comment by jmaister** [comment]
You can use the `removeColumns`option to remove all columns except the first one.

    removeColumns: [...], // Array of column indexes (from 0)

In your case it would be:

    removeColumns: [1, 2, 3, ...]

**Comment by eric-5512** [comment]
HI @jmaister  THANK YOU
