### ISSUE TITLE
How to use  in vue2.0 ? excel

### ISSUE THREAD

**Issue by Timnny** [jmaister/excellentexport#66]
When i use in vue2 , export xml file and open it ,there is nothing, empty

**Comment by jiutianlanyue** [comment]
yes

**Comment by jmaister** [comment]
Would you provide an example of how you use it with Vue2 ?

**Comment by sRect** [comment]
How to solve this problem?

**Comment by vuoriov4** [comment]
This works for me

    <button v-on:click="export()"></button>
...

    export() {
        var a = document.createElement('a');
        a.download = 'Reports.xls';
        a.onclick = function() {
            return ExcellentExport.excel(this, 'datatable', 'Reports')
        }
        a.click();
    }
