### ISSUE TITLE
Changing format make it buggy

### ISSUE THREAD

**Issue by P-R-O-O-F** [jmaister/excellentexport#669]
Hi, when i download it's an xls and everything look great but i need it to be an CSV (it's an obligation) but when i forced the change in format to csv its look like a mess, what can i do? Thanks! @jmaister

**Comment by jmaister** [comment]
What do you mean by CSV looks like a mess?
CSV looks like that, it is not going to be aligned. If you open it in Excel or OpenOffice it will look like an Excel file.
