### ISSUE TITLE
Question: do you support "grid" export?

### ISSUE THREAD

**Issue by jehon** [jmaister/excellentexport#672]
Thank you for this great project!

You can export tables into excel.

Can this plugin export css "grid" into excel too?

Thanks and have a great day

**Comment by jmaister** [comment]
It's not supported at the moment.

Would you share an example of one of your tables with a CSS grid? Then I can see how it could be converted into an array and work from there.

**Comment by jehon** [comment]
It is based on MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/grid

An example: https://jsfiddle.net/jehon/kqd2ac3s/1/

**Comment by jmaister** [comment]
I see this as a quite difficult task.

First, it is needed to parse the CSS assigned to the DOM object that is the container. According to the Mozilla page, these are all the options. And calculate how this affects each of the children of the container.

```css
/* <'grid-template'> values */
grid: none;
grid: "a" 100px "b" 1fr;
grid: [linename1] "a" 100px [linename2];
grid: "a" 200px "b" min-content;
grid: "a" minmax(100px, max-content) "b" 20%;
grid: 100px / 200px;
grid: minmax(400px, min-content) / repeat(auto-fill, 50px);

/* <'grid-template-rows'> /
   [ auto-flow && dense? ] <'grid-auto-columns'>? values */
grid: 200px / auto-flow;
grid: 30% / auto-flow dense;
grid: repeat(3, [line1 line2 line3] 200px) / auto-flow 300px;
grid: [line1] minmax(20em, max-content) / auto-flow dense 40%;

/* [ auto-flow && dense? ] <'grid-auto-rows'>? /
   <'grid-template-columns'> values */
grid: auto-flow / 200px;
grid: auto-flow dense / 30%;
grid: auto-flow 300px / repeat(3, [line1 line2 line3] 200px);
grid: auto-flow dense 40% / [line1] minmax(20em, max-content);

/* Global values */
grid: inherit;
grid: initial;
grid: revert;
grid: revert-layer;
grid: unset;
```

The second biggest problem is that some of the `grid` options are dependent on the size of the page and the cells. If you resize the page, the arrangement of the cells/columns will change.

I don't think this is a feasible task for this project.

**Comment by jmaister** [comment]
If you are developing the HTML of that page, you already have the data available. Can you make some data transformations to get an array? Then pass that array to ExcellentExport.

**Comment by jehon** [comment]
Yes, no problem... would have been a nice feature, but hard to implement yes
Thanks for your time
