### ISSUE TITLE
background color cell

### ISSUE THREAD

**Issue by Jnrmax202017** [jmaister/excellentexport#680]
Hello, I am grateful to use your library how I will could do to add more than 2 sheets to the file excel and also add the background-color to a cell of the exported file, thanks

**Comment by KiligFei** [comment]
ExcellentExport.convert(options, sheets); 
sheets is an array

**Comment by jmaister** [comment]
As @KiligFei said, that's the way to add sheets to the workbook.

This library does not support styling of the cells.
