### ISSUE TITLE
Possibility to select a CSV delimiter?

### ISSUE THREAD

**Issue by blackboxmedia** [jmaister/excellentexport#681]
in Version 1.5. you had a Feature called "Possibility to select a CSV delimiter."
I cannot find ANY Documentation on that topic or on how to set a the delimiter... 
could you add that to your docs please? OR tell me how to set the option?

Thank you

**Comment by jmaister** [comment]
As you are using the 1.5 version, I suppose you are using ExcellentExport.csv(...)

This is the method signature:

    csv: function(anchor:(HTMLAnchorElement|string), table:HTMLTableElement, delimiter?:string, newLine?:string) {

You can use the `delimiter` parameter to change it.

**Comment by AlpixTM** [comment]
Ist this also possible with the .convert function?
