### ISSUE TITLE
Add line before table

### ISSUE THREAD

**Issue by simplyBarbe** [jmaister/excellentexport#682]
How can i add a line/row before the exported table.
i use this code.
```
return ExcellentExport.convert({
    anchor: "anchorNewApi-xlsx-some",
    filename: "exportAntimafia",
    format: "xlsx"
}, [{
    name: 'Sheet number 1',
    from: {
        table: 'ContentPlaceHolder1_TableAntima'
    },
    fixValue: (value, row, col) => {
        return value.replace(/(<([^>]+)>)/gi, "");
    },
    removeColumns: [0, 1]
}])
```
i want to add a line and insert some text in it in the very first row.

**Comment by jmaister** [comment]
Yes, you can.

There is the fixArray parameter to modify the whole data array.

    fixArray?(array:any[][]): any[][]

There you can modify it by adding rows (array.push) or columns (array.forEach(...))
