### ISSUE TITLE
Unable to fix error: TypeError a is null

### ISSUE THREAD

**Issue by singhayushh** [jmaister/excellentexport#683]
Hello,
I am trying to implement excellentexport to my server-side-rendered ejs page, where tables are dynamically being created based on a `report` variable coming from the backend, which is an array of objects which define the table contents. The tables are each given a unique, alphanumeric id as well based on a subfield of report and the same subfield is being used to assign tables to different sheets while using excellentexport's convert function.

The javascript looks like this:

```ejs
    function exportCSV() {
        return ExcellentExport.convert(
            { 
                anchor: this, 
                filename: '<%= start.toLocaleString("default", { year: "numeric", month: "2-digit", day: "2-digit"  }) %>-to-<%= end.toLocaleString("default", { year: "numeric", month: "2-digit", day: "2-digit"  }) %>', 
                format: 'xlsx'
            }, 
            [
                <% for (const rep of report) { %>
                {
                    name: '<%= (rep.openingAnalytics._id.name).replace(/[^a-z0-9]/gi, '') %>',
                    from: {
                        table: '<%= (rep.openingAnalytics._id.name).replace(/[^a-z0-9]/gi, '') %>'
                    }
                },
                <% } %>
            ]
        );
    }
```

In the browser console, I can see excellentexport logging the different table names but the export is failing and I'm receiving the following error
```diff
- Uncaught Error: Error converting to xls. TypeError: a is null
    f https://cdn.jsdelivr.net/npm/excellentexport@3.4.3/dist/excellentexport.min.js:12
    convert https://cdn.jsdelivr.net/npm/excellentexport@3.4.3/dist/excellentexport.min.js:12
```

**Comment by jmaister** [comment]
How do you load the ExcellentExport library? Is it with an script tag? require? Other?
