### ISSUE TITLE
Is possible to change format number from 12,345.67 to 12.345,67

### ISSUE THREAD

**Issue by edikurniawan-dev** [jmaister/excellentexport#687]
Is possible to change format number from 12,345.67 to 12.345,67 like indonesian format number?

**Comment by juvian** [comment]
@edikurniawan-dev did you figure it out?

**Comment by jmaister** [comment]
Yes, it is possible since version 3.9.0.

Take a look to the README on the "Formats" section: https://github.com/jmaister/excellentexport#formats

**Comment by juvian** [comment]
@jmaister  I tried #.##0,00 and it didn't work (to have point as thousand separator and comma as decimal), not sure if that was wrong or excel does not support that. Ended up just converting values to string manually
