### ISSUE TITLE
Saving the file to the server

### ISSUE THREAD

**Issue by LizardWizardGB** [jmaister/excellentexport#688]
Is there a way to save the file onto the server, instead of downloading it to your local machine?

**Comment by jmaister** [comment]
This is quite a wide open question. Can you give more details?

**Comment by LizardWizardGB** [comment]
Instead of downloading the file onto my PC, is there a way to generate the excel and then save it onto the server instead?

**Comment by jmaister** [comment]
If you have the data in the server, you can just create the file and store it in the server directly. This library works only on the browser side.
