### ISSUE TITLE
I want to export my html table to xlsx instead of xls. Any support for this?

### ISSUE THREAD

**Issue by zruihao68** [jmaister/excellentexport#71]
### I want to export my html table to xlsx instead of xls. Any support for this?

**Comment by jmaister** [comment]
Adding download="file.xlsx" would change the file extension.

<a download="somedata.xlsx" href="#" onclick="return ExcellentExport.excel(this, 'datatable', 'Sheet Name Here');">Export to Excel</a>

The way the XLS is created does not allow to create XLSX without adding more JavaScript dependencies.

**Comment by jmaister** [comment]
I am thinking on adding dependencies but creating a distribution file compressed with Webpack.

**Comment by jmaister** [comment]
Resolved on 654f2340a2b1a407ef7b86733e62f880bce2e38a
