### ISSUE TITLE
How to use css style when export html to xls?

### ISSUE THREAD

**Issue by luisantoniojr** [jmaister/excellentexport#72]
Hi, first nice work!
I made a dynamic report using nodejs and angular 1.6. I can export a html table to xls, but when i need to use css style, this is not working, as you can see in the picture below. I tried a lot of things before i came here, if is not issue, pardon me.

![image](https://user-images.githubusercontent.com/2197380/30971256-cf188ab8-a43d-11e7-8378-e9ba29e19ca6.png)

**Comment by jmaister** [comment]
Data for enhancement of the new API: https://github.com/SheetJS/js-xlsx/blob/master/tests/write.js#L14-L19

**Comment by jmaister** [comment]
ExcellentExport library does not handle Excel styles.
