### ISSUE TITLE
It doesn't work well in ie8

### ISSUE THREAD

**Issue by seven7ma** [jmaister/excellentexport#73]
It's a small and usefull tool.
But the IE8 does not surport the btoa attribute,
Is there any solution?

**Comment by jmaister** [comment]
IE8 or lower do not support data: url schema. IE9 does not support data: url schema on links.

There is no way to do it in the browser. You'll need to create the Excel in the server side.

**Comment by seven7ma** [comment]
Thanks for your answer, i get it!
