### ISSUE TITLE
about vuejs

### ISSUE THREAD

**Issue by sunnoy** [jmaister/excellentexport#74]
how to use in vusjs?
my code

` import ExcellentExport from 'excellentexport';
        <a download="somedata.xls" href="#" onclick="dong(datatable)">Export to Excel</a>
methods:{
            dong:function (val) {
                return ExcellentExport.excel(this, val, 'recent');

            }

        }`
and it give me 
error
`Uncaught ReferenceError: dong is not defined`

**Comment by jmaister** [comment]
Would you add your HTML code ?
