### ISSUE TITLE
Unexpected token: keyword (const)

### ISSUE THREAD

**Issue by anrip** [jmaister/excellentexport#75]
**ng build --prod** 

show error

> 
> Parse error at www\vendor.bundle.js:101,0
> const ExcellentExport = function() {
> ^
> ERROR: Unexpected token: keyword (const)
>     at JS_Parse_Error.get (eval at <anonymous> (\node_modules\uglify-js\tools\node.js:21:1), <anonymous>:79:23)
>     at fatal (\node_modules\uglify-js\bin\uglifyjs:268:52)
>     at run (\node_modules\uglify-js\bin\uglifyjs:225:9)
>     at Object.<anonymous> (\node_modules\uglify-js\bin\uglifyjs:155:5)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.runMain (module.js:604:10)

**Comment by jmaister** [comment]
Use the file "dist/excellentexport.js". It is already compiled from ES6.
