### ISSUE TITLE
error "anchor is not defined"

### ISSUE THREAD

**Issue by cfregistry** [jmaister/excellentexport#78]
Hi, 
The location of my page is 1.1.1.1/sis/pag/rel/ar/page.html, but my url is 1.1.1.1/sis/rel/seg. When I inpect the execution, this error is displayed:
```
message
:
"anchor is not defined"

"ReferenceError: anchor is not defined↵    
at eval (eval at newApiArray (http://1.1.1.1/sis/rel/seg:14:9), <anonymous>:1:1)↵    
at newApiArray (http://1.1.1.1/sis/rel/seg:628:9)↵    
at HTMLButtonElement.onclick (http://1.1.1.1/sis/rel/seg:630:148)"
```

How can I fix this?

Thank you, and sorry for my english.
Best regards Cássio

**Comment by jmaister** [comment]
Can you show the code where you are using to call to ExcellentExport ?

**Comment by cfregistry** [comment]
Import js
`<script type="text/javascript" src="../pag/rel/Ar/excellentexport/dist/excellentexport.js"></script>`

```
<script>
   function newApiArray(format) {
       return ExcellentExport.convert({
             anchor: 'gerarAnalitico',
             filename: 'Seguros',
             format: format
         }, [{
            name: 'Seguros',
             from: {
                   array: [['line 1', 1234 , 'CN 你好'],
                             [ 'line 2', 1234.56 , 'JP こんにちは']
                         ]
               }
            }]);
    }</script>
<button  href='#' id='gerarAnalitico' onclick=\"return newApiArray('xlsx');\">Gerar analítico</button>
```

**Comment by jmaister** [comment]
This is not a bug, you have some syntax errors. Also, the library does not work with BUTTON only works with A.

Note the onclick without the backslash \ and changed 'button' to 'a':

    <a  href='#' id='gerarAnalitico' onclick="return newApiArray('xlsx');">Gerar analítico</a>
