### ISSUE TITLE
Limit of 3000 records per file?

### ISSUE THREAD

**Issue by lazmo88** [jmaister/excellentexport#81]
Great work with the library!

However, today I stumbled upon a surprising issue. I tried to export 10 000 rows of data, with 6 columns. So all together 60 000 cells. File that is created only contains 3000 rows / 6 columns.

Has this bug been figured out earlier?

API used is the latest xlsx one: <a download="somedata.xlsx" href="#" onclick="return ExcellentExport.convert({ anchor: this, filename: 'vouchers', format: 'xlsx'},[{name: 'Vouchers', from: {table: 'datatable'}}]);">

I did not have time to test other API's yet.

**Comment by jmaister** [comment]
Thank you.

There is not limit specified by the library.

How are you creating the Excel file? Would you share some of your code ?
