### ISSUE TITLE
How to use in Vue.js?

### ISSUE THREAD

**Issue by hedekun** [jmaister/excellentexport#82]
I don't know how to import the excellentexport.js

**Comment by alex2wong** [comment]
I believe you have solved this issue in last year..
```
const excellentExport = require('excellentexport');
```

**Comment by ykl124** [comment]
import ExcellentExport from 'excellentexport'

**Comment by jmaister** [comment]
Both previous answers are correct.
Also install the library with npm

    npm install excellentexport --save
