### ISSUE TITLE
Suggestion: Regular Expression to remove the links but keep the inner text

### ISSUE THREAD

**Issue by Shomrat-Gil** [jmaister/excellentexport#83]
Hello,
I have a suggestion: I modifies your script, adding a Regular Expression to extract inner text from link tags and remove the link.
My tables included navigation links that are not useful within Excel, but their content is needed.
Where the code says table:n.innerHTML
I edit it to be table:n.innerHTML.replace(/<[a|A][^>]*>|<\/[a|A]>/g,"")
There might be others that would need this feature, happy to share.
Thank you,
Gil

**Comment by jmaister** [comment]
This can be solved with the new configuration functions fixValue and fixData. Check the documentation and index.filters.html to see how they work.

Update to version 3.5.0 to use them.

Those functions can be used to manipulate the cell values before the Excel file is generated.
