### ISSUE TITLE
Could you add an example of cell / text formatting?

### ISSUE THREAD

**Issue by rtek1000** [jmaister/excellentexport#90]
Congratulations on the great work!

Would it be possible to add an example of formatting with:

- merged cells
- cell size
- centering text
- bold text
- select font
- select size font
- bold font
- cell borders

Which of these features is already available in the new API?

I saw that in issue 6, in the year 2014, was answered that these parameters would not be implemented, but, without being able to format cells and text, the API is more useful for knowing that it is possible to make it work well, but that it can not be used on a daily basis yet.

Thank you!

**Comment by rtek1000** [comment]
Would it be possible to load an excel file template?

With a preformatted file could it be simpler to edit the data?

Any examples of how to edit the data only? (text and numbers)

Thank you!

**Comment by rtek1000** [comment]
This project is for Android, but maybe it can help in code:

Read / Write Excel files on Android:
https://www.b4x.com/android/forum/threads/read-write-excel-files-on-android.25632/#content

A Java library for reading/writing Excel:
https://sourceforge.net/projects/jexcelapi/files/jexcelapi/2.6.12/

Thank you!

**Comment by jmaister** [comment]
This library does not aim to use it with any formatting.
