### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by Fi1osof** [jmaister/excellentexport#91]
Good day!

Thanks for awesome lib!

Unfortunately, does not work in SSR mode.

**Comment by Fi1osof** [comment]
My workaround: require in click function const ExcellentExport = require('excellentexport'); instead import in head of file.

**Comment by jmaister** [comment]
Never heard of it. What is SSR mode ?
Could you put an example ?

**Comment by Fi1osof** [comment]
@jmaister Server Side Rendering. When react app rendering via node-js in server, not in browser. https://medium.freecodecamp.org/server-side-rendering-your-react-app-in-three-simple-steps-7a82b95db82e

**Comment by jmaister** [comment]
I will see if "window" references can be removed.
Anyway, the idea of the library is to run on a browser.

**Comment by Fi1osof** [comment]
> Anyway, the idea of the library is to run on a browser.
An error occurs not only when run library, but event when "include ... from".

**Comment by jmaister** [comment]
Even using SSR, the library will run in the browser, when the user interacts with the page.
The server side should not execute any code of ExcellentExport.
