### ISSUE TITLE
Support convert in 2.10

### ISSUE THREAD

**Issue by alex2wong** [jmaister/excellentexport#92]
Hi team, 
   Can we support convert API when using v2.1.x. Since we do NOT want upgrade to big dist file in 3.x ( we do not need xlsx).  But we need export excel from Array, that would be much more flexible than from HTMLTableElement, especially for some icon/image in table cell which is expected to be exported as alt/hidden text. I believe that is the first choice since we do not support image in excel.

```
/// maybe like this.
excellentExport.excel(e.target, this.tableId, 'sheet 1', { enableHiddenHTML: true });
```
   btw, simply enable export hidden text for iconFont/image from its aria attr is a good solution, can I do that in v.2.1.x ?? Thanks a lot for this great repo.

**Comment by jmaister** [comment]
Not planning on add that support.
Please, add a Pull Request if you are working on that regard.
